default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "deploy" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  primary:
    <<: *default
    database: app_development
  queue:
    <<: *default
    database: app_development_queue
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: app_test
  queue:
    <<: *default
    database: app_test_queue
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    database: app_production
    username: <%= ENV.fetch("POSTGRES_USER") { "deploy" } %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: <%= ENV["POSTGRES_HOST"] %>
  queue:
    <<: *default
    database: app_production_queue
    migrations_paths: db/queue_migrate